import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import { ThemeProvider } from "@/context/ThemeContext";
import ClientProviderWrapper from "@/context/ClientProviderWrapper";

const nunito = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Countries data",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className={nunito.className} lang="en">
      <body>
        <ThemeProvider>
          <ClientProviderWrapper>
            <Header />
            {children}
          </ClientProviderWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
